name: lint
on: [push]
jobs:
  check lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - run: make lint